### PR TITLE
polkit rules: tweak to be ecma 5 compatible

### PR DESCRIPTION
**Pull request by alatiera**
Or how I lost a weekend debugging..

Polkit rules must be ecma 5 compatible [1]

* Use var instead of const for the array
* Use indexOf instead of includes

[1] https://gitlab.freedesktop.org/polkit/polkit/-/blob/master/docs/man/polkit.xml#L504

### CODE REVIEW

**Comment by wjt** [comment]
hey jenkins! this is ok to test

**Comment by wjt** [comment]
LGTM – I don't suppose you know of a decent way to lint these rules?

**Comment by wjt** [comment]
Is this a draft because you want to do some further testing?

**Comment by alatiera** [comment]
nope, there doesn't seem a way to validate them before hand, I am running a test build now.

**Comment by alatiera** [comment]
It works :tada:

**Review by wjt — APPROVED** [review]

**Pull request merged**
